// Curated baby-name dataset. Meanings are the widely documented, standard
// meanings for these well-known names; users are advised to verify with
// religious/linguistic sources before finalising a name.

export type Religion = "islamic" | "hindu" | "christian" | "sikh";
export type Gender = "boy" | "girl";

export type NameEntry = {
  name: string;
  gender: Gender;
  religion: Religion;
  meaning: string;
  origin: string;
  tag?: string;
};

export const RELIGION_LABELS: Record<Religion, string> = {
  islamic: "Islamic / Muslim",
  hindu: "Hindu",
  christian: "Christian",
  sikh: "Sikh",
};

export const NAMES: NameEntry[] = [
  // ---------- Islamic — boys ----------
  { name: "Muhammad", gender: "boy", religion: "islamic", meaning: "The praised one", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ahmad", gender: "boy", religion: "islamic", meaning: "Most praiseworthy", origin: "Arabic", tag: "Prophet's name" },
  { name: "Mustafa", gender: "boy", religion: "islamic", meaning: "The chosen one", origin: "Arabic", tag: "Prophet's title" },
  { name: "Adam", gender: "boy", religion: "islamic", meaning: "Made from earth; first man", origin: "Arabic/Hebrew", tag: "Prophet's name" },
  { name: "Idris", gender: "boy", religion: "islamic", meaning: "Studious, learned", origin: "Arabic", tag: "Prophet's name" },
  { name: "Nuh", gender: "boy", religion: "islamic", meaning: "Rest, comfort (Noah)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ibrahim", gender: "boy", religion: "islamic", meaning: "Father of many (Abraham)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ismail", gender: "boy", religion: "islamic", meaning: "God will hear (Ishmael)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ishaq", gender: "boy", religion: "islamic", meaning: "One who laughs (Isaac)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Yaqub", gender: "boy", religion: "islamic", meaning: "One who follows (Jacob)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Yusuf", gender: "boy", religion: "islamic", meaning: "God increases (Joseph)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Musa", gender: "boy", religion: "islamic", meaning: "Drawn out of water (Moses)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Harun", gender: "boy", religion: "islamic", meaning: "Exalted (Aaron)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Dawud", gender: "boy", religion: "islamic", meaning: "Beloved (David)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Sulaiman", gender: "boy", religion: "islamic", meaning: "Man of peace (Solomon)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ayyub", gender: "boy", religion: "islamic", meaning: "Patient, returning to God (Job)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Yunus", gender: "boy", religion: "islamic", meaning: "Dove (Jonah)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Zakariya", gender: "boy", religion: "islamic", meaning: "God has remembered (Zechariah)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Yahya", gender: "boy", religion: "islamic", meaning: "God is gracious; alive (John)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Isa", gender: "boy", religion: "islamic", meaning: "God is salvation (Jesus)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ilyas", gender: "boy", religion: "islamic", meaning: "My God is Yahweh (Elijah)", origin: "Arabic", tag: "Prophet's name" },
  { name: "Salih", gender: "boy", religion: "islamic", meaning: "Righteous, virtuous", origin: "Arabic", tag: "Prophet's name" },
  { name: "Shuaib", gender: "boy", religion: "islamic", meaning: "One who shows the way", origin: "Arabic", tag: "Prophet's name" },
  { name: "Hud", gender: "boy", religion: "islamic", meaning: "One who repents", origin: "Arabic", tag: "Prophet's name" },
  { name: "Ali", gender: "boy", religion: "islamic", meaning: "Exalted, noble", origin: "Arabic", tag: "Sahabi name" },
  { name: "Umar", gender: "boy", religion: "islamic", meaning: "Flourishing, long-lived", origin: "Arabic", tag: "Sahabi name" },
  { name: "Uthman", gender: "boy", religion: "islamic", meaning: "Wise, most powerful", origin: "Arabic", tag: "Sahabi name" },
  { name: "Hamza", gender: "boy", religion: "islamic", meaning: "Lion, strong and steadfast", origin: "Arabic", tag: "Sahabi name" },
  { name: "Bilal", gender: "boy", religion: "islamic", meaning: "Water, moistening", origin: "Arabic", tag: "Sahabi name" },
  { name: "Khalid", gender: "boy", religion: "islamic", meaning: "Eternal, immortal", origin: "Arabic", tag: "Sahabi name" },
  { name: "Zaid", gender: "boy", religion: "islamic", meaning: "Growth, abundance", origin: "Arabic", tag: "Sahabi name" },
  { name: "Talha", gender: "boy", religion: "islamic", meaning: "A kind of fruitful tree", origin: "Arabic", tag: "Sahabi name" },
  { name: "Zubair", gender: "boy", religion: "islamic", meaning: "Strong, intelligent", origin: "Arabic", tag: "Sahabi name" },
  { name: "Saad", gender: "boy", religion: "islamic", meaning: "Felicity, good fortune", origin: "Arabic", tag: "Sahabi name" },
  { name: "Muadh", gender: "boy", religion: "islamic", meaning: "Protected, sheltered", origin: "Arabic", tag: "Sahabi name" },
  { name: "Anas", gender: "boy", religion: "islamic", meaning: "Affection, friendliness", origin: "Arabic", tag: "Sahabi name" },
  { name: "Abbas", gender: "boy", religion: "islamic", meaning: "Lion, stern-faced", origin: "Arabic", tag: "Sahabi name" },
  { name: "Jafar", gender: "boy", religion: "islamic", meaning: "Stream, small river", origin: "Arabic", tag: "Sahabi name" },
  { name: "Salman", gender: "boy", religion: "islamic", meaning: "Safe, secure", origin: "Arabic", tag: "Sahabi name" },
  { name: "Ammar", gender: "boy", religion: "islamic", meaning: "Long-lived, builder", origin: "Arabic", tag: "Sahabi name" },
  { name: "Hassan", gender: "boy", religion: "islamic", meaning: "Handsome, good", origin: "Arabic" },
  { name: "Hussain", gender: "boy", religion: "islamic", meaning: "Beautiful, good (diminutive)", origin: "Arabic" },
  { name: "Tariq", gender: "boy", religion: "islamic", meaning: "Morning star; one who knocks", origin: "Arabic" },
  { name: "Faisal", gender: "boy", religion: "islamic", meaning: "Decisive, a judge", origin: "Arabic" },
  { name: "Farhan", gender: "boy", religion: "islamic", meaning: "Happy, joyful", origin: "Arabic" },
  { name: "Imran", gender: "boy", religion: "islamic", meaning: "Prosperity; family of Maryam", origin: "Arabic" },
  { name: "Rayyan", gender: "boy", religion: "islamic", meaning: "Gate of Paradise for those who fast", origin: "Arabic" },
  { name: "Ayaan", gender: "boy", religion: "islamic", meaning: "Gift of God; time, era", origin: "Arabic" },
  { name: "Zayan", gender: "boy", religion: "islamic", meaning: "Beautifier, graceful", origin: "Arabic" },
  { name: "Rehan", gender: "boy", religion: "islamic", meaning: "Sweet basil, fragrant plant", origin: "Arabic" },
  { name: "Arsalan", gender: "boy", religion: "islamic", meaning: "Lion, fearless", origin: "Persian/Turkish" },
  { name: "Danish", gender: "boy", religion: "islamic", meaning: "Knowledge, wisdom", origin: "Persian" },
  { name: "Nadeem", gender: "boy", religion: "islamic", meaning: "Companion, friend", origin: "Arabic" },
  { name: "Rashid", gender: "boy", religion: "islamic", meaning: "Rightly guided", origin: "Arabic" },
  { name: "Sameer", gender: "boy", religion: "islamic", meaning: "Pleasant companion in evening talk", origin: "Arabic" },
  { name: "Shahid", gender: "boy", religion: "islamic", meaning: "Witness", origin: "Arabic" },
  { name: "Waseem", gender: "boy", religion: "islamic", meaning: "Handsome, graceful", origin: "Arabic" },
  { name: "Arham", gender: "boy", religion: "islamic", meaning: "Merciful, compassionate", origin: "Arabic" },
  { name: "Aariz", gender: "boy", religion: "islamic", meaning: "Respectable, intelligent man", origin: "Arabic" },
  { name: "Faiz", gender: "boy", religion: "islamic", meaning: "Grace, abundance", origin: "Arabic" },

  // ---------- Islamic — girls ----------
  { name: "Fatima", gender: "girl", religion: "islamic", meaning: "One who abstains; captivating", origin: "Arabic", tag: "Prophet's daughter" },
  { name: "Aisha", gender: "girl", religion: "islamic", meaning: "Alive, living, prosperous", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Khadija", gender: "girl", religion: "islamic", meaning: "Early baby; trustworthy", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Maryam", gender: "girl", religion: "islamic", meaning: "Beloved, devoted to God (Mary)", origin: "Arabic/Hebrew", tag: "Quranic name" },
  { name: "Zainab", gender: "girl", religion: "islamic", meaning: "Fragrant flowering plant", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Ruqayyah", gender: "girl", religion: "islamic", meaning: "Gentle, ascending", origin: "Arabic", tag: "Prophet's daughter" },
  { name: "Hafsa", gender: "girl", religion: "islamic", meaning: "Young lioness; gathering", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Safiya", gender: "girl", religion: "islamic", meaning: "Pure, sincere friend", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Sumayya", gender: "girl", religion: "islamic", meaning: "High above, exalted", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Asma", gender: "girl", religion: "islamic", meaning: "Exalted, lofty", origin: "Arabic", tag: "Sahabiyat name" },
  { name: "Amina", gender: "girl", religion: "islamic", meaning: "Trustworthy, faithful", origin: "Arabic", tag: "Prophet's mother" },
  { name: "Halima", gender: "girl", religion: "islamic", meaning: "Gentle, patient", origin: "Arabic", tag: "Prophet's foster mother" },
  { name: "Sana", gender: "girl", religion: "islamic", meaning: "Radiance, brilliance", origin: "Arabic" },
  { name: "Sara", gender: "girl", religion: "islamic", meaning: "Princess, noble lady", origin: "Arabic/Hebrew" },
  { name: "Hana", gender: "girl", religion: "islamic", meaning: "Happiness, bliss", origin: "Arabic" },
  { name: "Iqra", gender: "girl", religion: "islamic", meaning: "Read, recite", origin: "Arabic" },
  { name: "Zara", gender: "girl", religion: "islamic", meaning: "Radiance, blooming flower", origin: "Arabic" },
  { name: "Noor", gender: "girl", religion: "islamic", meaning: "Light, divine light", origin: "Arabic" },
  { name: "Rabia", gender: "girl", religion: "islamic", meaning: "Spring, fourth", origin: "Arabic" },
  { name: "Yasmin", gender: "girl", religion: "islamic", meaning: "Jasmine flower", origin: "Persian" },
  { name: "Farah", gender: "girl", religion: "islamic", meaning: "Joy, happiness", origin: "Arabic" },
  { name: "Bushra", gender: "girl", religion: "islamic", meaning: "Good news, glad tidings", origin: "Arabic" },
  { name: "Rahma", gender: "girl", religion: "islamic", meaning: "Mercy, compassion", origin: "Arabic" },
  { name: "Aaliyah", gender: "girl", religion: "islamic", meaning: "Exalted, high-ranking", origin: "Arabic" },
  { name: "Amira", gender: "girl", religion: "islamic", meaning: "Princess, leader", origin: "Arabic" },
  { name: "Anaya", gender: "girl", religion: "islamic", meaning: "Care, protection", origin: "Arabic" },
  { name: "Dua", gender: "girl", religion: "islamic", meaning: "Prayer, supplication", origin: "Arabic" },
  { name: "Iman", gender: "girl", religion: "islamic", meaning: "Faith, belief", origin: "Arabic" },
  { name: "Inaya", gender: "girl", religion: "islamic", meaning: "Concern, care, protection", origin: "Arabic" },
  { name: "Kulsum", gender: "girl", religion: "islamic", meaning: "Full-cheeked, beautiful face", origin: "Arabic", tag: "Prophet's daughter (Umm Kulthum)" },
  { name: "Laiba", gender: "girl", religion: "islamic", meaning: "Angel of heaven, beautiful", origin: "Arabic/Urdu" },
  { name: "Mahnoor", gender: "girl", religion: "islamic", meaning: "Light of the moon", origin: "Persian/Urdu" },
  { name: "Madiha", gender: "girl", religion: "islamic", meaning: "Praiseworthy", origin: "Arabic" },
  { name: "Nabila", gender: "girl", religion: "islamic", meaning: "Noble, honourable", origin: "Arabic" },
  { name: "Nadia", gender: "girl", religion: "islamic", meaning: "Caller, announcer; hope", origin: "Arabic" },
  { name: "Naima", gender: "girl", religion: "islamic", meaning: "Blessing, living a soft life", origin: "Arabic" },
  { name: "Rida", gender: "girl", religion: "islamic", meaning: "Contentment, divine acceptance", origin: "Arabic" },
  { name: "Sadia", gender: "girl", religion: "islamic", meaning: "Fortunate, blessed", origin: "Arabic" },
  { name: "Saira", gender: "girl", religion: "islamic", meaning: "Traveller, one who journeys", origin: "Arabic" },
  { name: "Samina", gender: "girl", religion: "islamic", meaning: "Precious, valuable", origin: "Arabic" },
  { name: "Shifa", gender: "girl", religion: "islamic", meaning: "Healing, cure", origin: "Arabic" },
  { name: "Tahira", gender: "girl", religion: "islamic", meaning: "Pure, chaste", origin: "Arabic" },
  { name: "Umaima", gender: "girl", religion: "islamic", meaning: "Little mother", origin: "Arabic" },
  { name: "Wafa", gender: "girl", religion: "islamic", meaning: "Loyalty, faithfulness", origin: "Arabic" },
  { name: "Zoya", gender: "girl", religion: "islamic", meaning: "Life, alive, loving", origin: "Persian" },
  { name: "Haniya", gender: "girl", religion: "islamic", meaning: "Pleasant, happy", origin: "Arabic" },
  { name: "Areeba", gender: "girl", religion: "islamic", meaning: "Wise, intelligent", origin: "Arabic" },
  { name: "Fiza", gender: "girl", religion: "islamic", meaning: "Breeze, open atmosphere", origin: "Arabic/Urdu" },
  { name: "Alina", gender: "girl", religion: "islamic", meaning: "Beautiful, soft, delicate", origin: "Arabic" },
  { name: "Hoorain", gender: "girl", religion: "islamic", meaning: "Maidens of Paradise", origin: "Arabic/Urdu" },
  { name: "Ayat", gender: "girl", religion: "islamic", meaning: "Verses, signs of God", origin: "Arabic" },
  { name: "Sumaira", gender: "girl", religion: "islamic", meaning: "Brownish, diminutive of Samra", origin: "Arabic" },

  // ---------- Hindu — boys ----------
  { name: "Aarav", gender: "boy", religion: "hindu", meaning: "Peaceful, calm; melodious sound", origin: "Sanskrit" },
  { name: "Vivaan", gender: "boy", religion: "hindu", meaning: "Full of life; rays of the morning sun", origin: "Sanskrit" },
  { name: "Aditya", gender: "boy", religion: "hindu", meaning: "The sun; son of Aditi", origin: "Sanskrit" },
  { name: "Arjun", gender: "boy", religion: "hindu", meaning: "Bright, shining; the Pandava archer", origin: "Sanskrit" },
  { name: "Krishna", gender: "boy", religion: "hindu", meaning: "Dark, all-attractive; Lord Krishna", origin: "Sanskrit" },
  { name: "Rohan", gender: "boy", religion: "hindu", meaning: "Ascending, growing", origin: "Sanskrit" },
  { name: "Karan", gender: "boy", religion: "hindu", meaning: "Clever, skilful; the warrior Karna", origin: "Sanskrit" },
  { name: "Rahul", gender: "boy", religion: "hindu", meaning: "Efficient, conqueror of miseries", origin: "Sanskrit" },
  { name: "Ishaan", gender: "boy", religion: "hindu", meaning: "The sun; a name of Lord Shiva", origin: "Sanskrit" },
  { name: "Vihaan", gender: "boy", religion: "hindu", meaning: "Dawn, morning", origin: "Sanskrit" },
  { name: "Reyansh", gender: "boy", religion: "hindu", meaning: "Ray of light; part of Lord Vishnu", origin: "Sanskrit" },
  { name: "Shaurya", gender: "boy", religion: "hindu", meaning: "Bravery, valour", origin: "Sanskrit" },
  { name: "Atharv", gender: "boy", religion: "hindu", meaning: "Knowledge; the Atharva Veda", origin: "Sanskrit" },
  { name: "Advik", gender: "boy", religion: "hindu", meaning: "Unique, unprecedented", origin: "Sanskrit" },
  { name: "Pranav", gender: "boy", religion: "hindu", meaning: "The sacred syllable Om", origin: "Sanskrit" },
  { name: "Dhruv", gender: "boy", religion: "hindu", meaning: "Pole star; firm, immovable", origin: "Sanskrit" },
  { name: "Ansh", gender: "boy", religion: "hindu", meaning: "Portion, part (of the divine)", origin: "Sanskrit" },
  { name: "Harsh", gender: "boy", religion: "hindu", meaning: "Happiness, joy", origin: "Sanskrit" },
  { name: "Yash", gender: "boy", religion: "hindu", meaning: "Fame, glory, success", origin: "Sanskrit" },
  { name: "Ved", gender: "boy", religion: "hindu", meaning: "Sacred knowledge, the Vedas", origin: "Sanskrit" },
  { name: "Om", gender: "boy", religion: "hindu", meaning: "The primordial sacred sound", origin: "Sanskrit" },
  { name: "Shiv", gender: "boy", religion: "hindu", meaning: "Auspicious one; Lord Shiva", origin: "Sanskrit" },
  { name: "Rudra", gender: "boy", religion: "hindu", meaning: "The fierce one; a form of Shiva", origin: "Sanskrit" },
  { name: "Aryan", gender: "boy", religion: "hindu", meaning: "Noble, honourable", origin: "Sanskrit" },
  { name: "Nikhil", gender: "boy", religion: "hindu", meaning: "Complete, whole, entire", origin: "Sanskrit" },
  { name: "Vikram", gender: "boy", religion: "hindu", meaning: "Valour, prowess", origin: "Sanskrit" },
  { name: "Vijay", gender: "boy", religion: "hindu", meaning: "Victory", origin: "Sanskrit" },
  { name: "Ajay", gender: "boy", religion: "hindu", meaning: "Unconquerable, invincible", origin: "Sanskrit" },
  { name: "Sanjay", gender: "boy", religion: "hindu", meaning: "Triumphant, completely victorious", origin: "Sanskrit" },
  { name: "Manoj", gender: "boy", religion: "hindu", meaning: "Born of the mind; Kamadeva", origin: "Sanskrit" },
  { name: "Anil", gender: "boy", religion: "hindu", meaning: "Wind, god of air", origin: "Sanskrit" },
  { name: "Sunil", gender: "boy", religion: "hindu", meaning: "Deep blue, sapphire", origin: "Sanskrit" },
  { name: "Deepak", gender: "boy", religion: "hindu", meaning: "Lamp, source of light", origin: "Sanskrit" },
  { name: "Ashok", gender: "boy", religion: "hindu", meaning: "Without sorrow", origin: "Sanskrit" },
  { name: "Ravi", gender: "boy", religion: "hindu", meaning: "The sun", origin: "Sanskrit" },
  { name: "Kiran", gender: "boy", religion: "hindu", meaning: "Ray of light", origin: "Sanskrit" },
  { name: "Gaurav", gender: "boy", religion: "hindu", meaning: "Pride, honour, respect", origin: "Sanskrit" },
  { name: "Sachin", gender: "boy", religion: "hindu", meaning: "Pure, existence; a name of Shiva", origin: "Sanskrit" },
  { name: "Varun", gender: "boy", religion: "hindu", meaning: "God of water and oceans", origin: "Sanskrit" },
  { name: "Tarun", gender: "boy", religion: "hindu", meaning: "Young, youthful", origin: "Sanskrit" },
  { name: "Naveen", gender: "boy", religion: "hindu", meaning: "New, fresh", origin: "Sanskrit" },
  { name: "Mohan", gender: "boy", religion: "hindu", meaning: "Charming, enchanting; Krishna", origin: "Sanskrit" },
  { name: "Gopal", gender: "boy", religion: "hindu", meaning: "Cowherd; a name of Krishna", origin: "Sanskrit" },
  { name: "Madhav", gender: "boy", religion: "hindu", meaning: "Sweet like honey; Krishna", origin: "Sanskrit" },
  { name: "Keshav", gender: "boy", religion: "hindu", meaning: "One with beautiful hair; Krishna", origin: "Sanskrit" },
  { name: "Hari", gender: "boy", religion: "hindu", meaning: "Remover of sins; Vishnu", origin: "Sanskrit" },
  { name: "Ganesh", gender: "boy", religion: "hindu", meaning: "Lord of the ganas; Lord Ganesha", origin: "Sanskrit" },
  { name: "Rajesh", gender: "boy", religion: "hindu", meaning: "King of kings, ruler", origin: "Sanskrit" },
  { name: "Suresh", gender: "boy", religion: "hindu", meaning: "Lord of the gods (Indra)", origin: "Sanskrit" },
  { name: "Ramesh", gender: "boy", religion: "hindu", meaning: "Lord of Rama (Lakshmi); Vishnu", origin: "Sanskrit" },
  { name: "Mahesh", gender: "boy", religion: "hindu", meaning: "Great lord; a name of Shiva", origin: "Sanskrit" },
  { name: "Ram", gender: "boy", religion: "hindu", meaning: "Pleasing, charming; Lord Rama", origin: "Sanskrit" },

  // ---------- Hindu — girls ----------
  { name: "Ananya", gender: "girl", religion: "hindu", meaning: "Unique, matchless", origin: "Sanskrit" },
  { name: "Aadhya", gender: "girl", religion: "hindu", meaning: "First power; a name of Durga", origin: "Sanskrit" },
  { name: "Saanvi", gender: "girl", religion: "hindu", meaning: "A name of Goddess Lakshmi", origin: "Sanskrit" },
  { name: "Aaradhya", gender: "girl", religion: "hindu", meaning: "Worshipped, adored", origin: "Sanskrit" },
  { name: "Diya", gender: "girl", religion: "hindu", meaning: "Lamp, light", origin: "Sanskrit" },
  { name: "Pari", gender: "girl", religion: "hindu", meaning: "Fairy, angel", origin: "Persian/Hindi" },
  { name: "Anika", gender: "girl", religion: "hindu", meaning: "Graceful; a name of Durga", origin: "Sanskrit" },
  { name: "Navya", gender: "girl", religion: "hindu", meaning: "New, young, praiseworthy", origin: "Sanskrit" },
  { name: "Ishita", gender: "girl", religion: "hindu", meaning: "Mastery, superiority", origin: "Sanskrit" },
  { name: "Kavya", gender: "girl", religion: "hindu", meaning: "Poetry, poem", origin: "Sanskrit" },
  { name: "Riya", gender: "girl", religion: "hindu", meaning: "Singer, graceful", origin: "Sanskrit" },
  { name: "Siya", gender: "girl", religion: "hindu", meaning: "Goddess Sita", origin: "Sanskrit" },
  { name: "Tara", gender: "girl", religion: "hindu", meaning: "Star; a goddess", origin: "Sanskrit" },
  { name: "Meera", gender: "girl", religion: "hindu", meaning: "Devotee of Krishna; prosperous", origin: "Sanskrit" },
  { name: "Radha", gender: "girl", religion: "hindu", meaning: "Success; beloved of Krishna", origin: "Sanskrit" },
  { name: "Sita", gender: "girl", religion: "hindu", meaning: "Furrow; wife of Lord Rama", origin: "Sanskrit" },
  { name: "Gauri", gender: "girl", religion: "hindu", meaning: "Fair one; Goddess Parvati", origin: "Sanskrit" },
  { name: "Parvati", gender: "girl", religion: "hindu", meaning: "Daughter of the mountain", origin: "Sanskrit" },
  { name: "Lakshmi", gender: "girl", religion: "hindu", meaning: "Goddess of wealth and fortune", origin: "Sanskrit" },
  { name: "Saraswati", gender: "girl", religion: "hindu", meaning: "Goddess of knowledge and arts", origin: "Sanskrit" },
  { name: "Durga", gender: "girl", religion: "hindu", meaning: "Invincible; the warrior goddess", origin: "Sanskrit" },
  { name: "Pooja", gender: "girl", religion: "hindu", meaning: "Worship, prayer", origin: "Sanskrit" },
  { name: "Priya", gender: "girl", religion: "hindu", meaning: "Beloved, dear one", origin: "Sanskrit" },
  { name: "Neha", gender: "girl", religion: "hindu", meaning: "Love, affection; rain", origin: "Sanskrit" },
  { name: "Sneha", gender: "girl", religion: "hindu", meaning: "Affection, tenderness", origin: "Sanskrit" },
  { name: "Shreya", gender: "girl", religion: "hindu", meaning: "Auspicious, excellent", origin: "Sanskrit" },
  { name: "Divya", gender: "girl", religion: "hindu", meaning: "Divine, heavenly", origin: "Sanskrit" },
  { name: "Nisha", gender: "girl", religion: "hindu", meaning: "Night", origin: "Sanskrit" },
  { name: "Usha", gender: "girl", religion: "hindu", meaning: "Dawn", origin: "Sanskrit" },
  { name: "Asha", gender: "girl", religion: "hindu", meaning: "Hope, wish", origin: "Sanskrit" },
  { name: "Rekha", gender: "girl", religion: "hindu", meaning: "Line, streak of beauty", origin: "Sanskrit" },
  { name: "Geeta", gender: "girl", religion: "hindu", meaning: "Song; the Bhagavad Gita", origin: "Sanskrit" },
  { name: "Anjali", gender: "girl", religion: "hindu", meaning: "Offering with joined hands", origin: "Sanskrit" },
  { name: "Aarti", gender: "girl", religion: "hindu", meaning: "Ritual of light, worship", origin: "Sanskrit" },
  { name: "Bhavna", gender: "girl", religion: "hindu", meaning: "Feeling, emotion, devotion", origin: "Sanskrit" },
  { name: "Chitra", gender: "girl", religion: "hindu", meaning: "Picture; a nakshatra (star)", origin: "Sanskrit" },
  { name: "Deepika", gender: "girl", religion: "hindu", meaning: "Little lamp, light", origin: "Sanskrit" },
  { name: "Ganga", gender: "girl", religion: "hindu", meaning: "The sacred river Ganges", origin: "Sanskrit" },
  { name: "Indira", gender: "girl", religion: "hindu", meaning: "Beauty; a name of Lakshmi", origin: "Sanskrit" },
  { name: "Jaya", gender: "girl", religion: "hindu", meaning: "Victory; a name of Durga", origin: "Sanskrit" },
  { name: "Kajal", gender: "girl", religion: "hindu", meaning: "Kohl, eye decoration", origin: "Sanskrit/Hindi" },
  { name: "Lata", gender: "girl", religion: "hindu", meaning: "Creeper, vine", origin: "Sanskrit" },
  { name: "Madhuri", gender: "girl", religion: "hindu", meaning: "Sweetness", origin: "Sanskrit" },
  { name: "Nandini", gender: "girl", religion: "hindu", meaning: "Daughter; the sacred cow", origin: "Sanskrit" },
  { name: "Pallavi", gender: "girl", religion: "hindu", meaning: "New leaves, blossoming", origin: "Sanskrit" },
  { name: "Rani", gender: "girl", religion: "hindu", meaning: "Queen", origin: "Sanskrit/Hindi" },
  { name: "Swati", gender: "girl", religion: "hindu", meaning: "A nakshatra (star)", origin: "Sanskrit" },
  { name: "Trisha", gender: "girl", religion: "hindu", meaning: "Thirst, desire; noble", origin: "Sanskrit" },
  { name: "Vidya", gender: "girl", religion: "hindu", meaning: "Knowledge, learning", origin: "Sanskrit" },
  { name: "Yamini", gender: "girl", religion: "hindu", meaning: "Night", origin: "Sanskrit" },
  { name: "Vaani", gender: "girl", religion: "hindu", meaning: "Speech; Goddess Saraswati", origin: "Sanskrit" },
  { name: "Ira", gender: "girl", religion: "hindu", meaning: "Earth; a name of Saraswati", origin: "Sanskrit" },

  // ---------- Christian — boys ----------
  { name: "Matthew", gender: "boy", religion: "christian", meaning: "Gift of God", origin: "Hebrew", tag: "Apostle / Gospel writer" },
  { name: "Mark", gender: "boy", religion: "christian", meaning: "Dedicated to Mars; polite", origin: "Latin", tag: "Gospel writer" },
  { name: "Luke", gender: "boy", religion: "christian", meaning: "Light-giving, from Lucania", origin: "Greek", tag: "Gospel writer" },
  { name: "John", gender: "boy", religion: "christian", meaning: "God is gracious", origin: "Hebrew", tag: "Apostle / Gospel writer" },
  { name: "Peter", gender: "boy", religion: "christian", meaning: "Rock, stone", origin: "Greek", tag: "Apostle" },
  { name: "Paul", gender: "boy", religion: "christian", meaning: "Small, humble", origin: "Latin", tag: "Apostle" },
  { name: "James", gender: "boy", religion: "christian", meaning: "Supplanter (from Jacob)", origin: "Hebrew", tag: "Apostle" },
  { name: "Andrew", gender: "boy", religion: "christian", meaning: "Manly, brave", origin: "Greek", tag: "Apostle" },
  { name: "Philip", gender: "boy", religion: "christian", meaning: "Lover of horses", origin: "Greek", tag: "Apostle" },
  { name: "Thomas", gender: "boy", religion: "christian", meaning: "Twin", origin: "Aramaic", tag: "Apostle" },
  { name: "Simon", gender: "boy", religion: "christian", meaning: "He has heard", origin: "Hebrew", tag: "Apostle" },
  { name: "Stephen", gender: "boy", religion: "christian", meaning: "Crown, garland", origin: "Greek", tag: "First martyr" },
  { name: "Timothy", gender: "boy", religion: "christian", meaning: "Honouring God", origin: "Greek" },
  { name: "Daniel", gender: "boy", religion: "christian", meaning: "God is my judge", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "David", gender: "boy", religion: "christian", meaning: "Beloved", origin: "Hebrew", tag: "Biblical king" },
  { name: "Samuel", gender: "boy", religion: "christian", meaning: "God has heard", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "Joseph", gender: "boy", religion: "christian", meaning: "God will increase", origin: "Hebrew", tag: "Biblical name" },
  { name: "Joshua", gender: "boy", religion: "christian", meaning: "The Lord is salvation", origin: "Hebrew", tag: "Biblical name" },
  { name: "Caleb", gender: "boy", religion: "christian", meaning: "Whole-hearted, faithful", origin: "Hebrew", tag: "Biblical name" },
  { name: "Aaron", gender: "boy", religion: "christian", meaning: "Exalted, strong", origin: "Hebrew", tag: "Biblical name" },
  { name: "Benjamin", gender: "boy", religion: "christian", meaning: "Son of the right hand", origin: "Hebrew", tag: "Biblical name" },
  { name: "Nathan", gender: "boy", religion: "christian", meaning: "He gave, gift", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "Noah", gender: "boy", religion: "christian", meaning: "Rest, comfort", origin: "Hebrew", tag: "Biblical name" },
  { name: "Isaac", gender: "boy", religion: "christian", meaning: "He will laugh", origin: "Hebrew", tag: "Biblical name" },
  { name: "Jacob", gender: "boy", religion: "christian", meaning: "Supplanter, holder of the heel", origin: "Hebrew", tag: "Biblical name" },
  { name: "Michael", gender: "boy", religion: "christian", meaning: "Who is like God?", origin: "Hebrew", tag: "Archangel" },
  { name: "Gabriel", gender: "boy", religion: "christian", meaning: "God is my strength", origin: "Hebrew", tag: "Archangel" },
  { name: "Raphael", gender: "boy", religion: "christian", meaning: "God has healed", origin: "Hebrew", tag: "Archangel" },
  { name: "Christopher", gender: "boy", religion: "christian", meaning: "Bearer of Christ", origin: "Greek" },
  { name: "Nicholas", gender: "boy", religion: "christian", meaning: "Victory of the people", origin: "Greek", tag: "Saint's name" },
  { name: "Anthony", gender: "boy", religion: "christian", meaning: "Priceless, praiseworthy", origin: "Latin", tag: "Saint's name" },
  { name: "Francis", gender: "boy", religion: "christian", meaning: "Free man, Frenchman", origin: "Latin", tag: "Saint's name" },
  { name: "Dominic", gender: "boy", religion: "christian", meaning: "Belonging to the Lord", origin: "Latin", tag: "Saint's name" },
  { name: "Sebastian", gender: "boy", religion: "christian", meaning: "Venerable, revered", origin: "Greek", tag: "Saint's name" },
  { name: "Vincent", gender: "boy", religion: "christian", meaning: "Conquering", origin: "Latin", tag: "Saint's name" },
  { name: "Patrick", gender: "boy", religion: "christian", meaning: "Nobleman", origin: "Latin", tag: "Saint's name" },
  { name: "George", gender: "boy", religion: "christian", meaning: "Farmer, earth-worker", origin: "Greek", tag: "Saint's name" },
  { name: "Edward", gender: "boy", religion: "christian", meaning: "Wealthy guardian", origin: "English" },
  { name: "William", gender: "boy", religion: "christian", meaning: "Resolute protector", origin: "Germanic" },
  { name: "Henry", gender: "boy", religion: "christian", meaning: "Ruler of the home", origin: "Germanic" },
  { name: "Charles", gender: "boy", religion: "christian", meaning: "Free man", origin: "Germanic" },
  { name: "Robert", gender: "boy", religion: "christian", meaning: "Bright fame", origin: "Germanic" },
  { name: "Alexander", gender: "boy", religion: "christian", meaning: "Defender of the people", origin: "Greek" },
  { name: "Jonathan", gender: "boy", religion: "christian", meaning: "God has given", origin: "Hebrew", tag: "Biblical name" },
  { name: "Ethan", gender: "boy", religion: "christian", meaning: "Firm, enduring", origin: "Hebrew", tag: "Biblical name" },
  { name: "Elijah", gender: "boy", religion: "christian", meaning: "My God is Yahweh", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "Isaiah", gender: "boy", religion: "christian", meaning: "God is salvation", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "Jeremiah", gender: "boy", religion: "christian", meaning: "God will exalt", origin: "Hebrew", tag: "Biblical prophet" },
  { name: "Levi", gender: "boy", religion: "christian", meaning: "Joined, attached", origin: "Hebrew", tag: "Biblical name" },
  { name: "Abraham", gender: "boy", religion: "christian", meaning: "Father of many nations", origin: "Hebrew", tag: "Biblical name" },
  { name: "Xavier", gender: "boy", religion: "christian", meaning: "New house, bright", origin: "Basque", tag: "Saint's name" },
  { name: "Emmanuel", gender: "boy", religion: "christian", meaning: "God is with us", origin: "Hebrew", tag: "Biblical name" },

  // ---------- Christian — girls ----------
  { name: "Mary", gender: "girl", religion: "christian", meaning: "Beloved, wished-for child", origin: "Hebrew", tag: "Mother of Jesus" },
  { name: "Martha", gender: "girl", religion: "christian", meaning: "Lady, mistress of the house", origin: "Aramaic", tag: "Biblical name" },
  { name: "Elizabeth", gender: "girl", religion: "christian", meaning: "God is my oath", origin: "Hebrew", tag: "Biblical name" },
  { name: "Anna", gender: "girl", religion: "christian", meaning: "Grace, favour", origin: "Hebrew", tag: "Biblical name" },
  { name: "Hannah", gender: "girl", religion: "christian", meaning: "Grace of God", origin: "Hebrew", tag: "Biblical name" },
  { name: "Sarah", gender: "girl", religion: "christian", meaning: "Princess, noblewoman", origin: "Hebrew", tag: "Biblical name" },
  { name: "Rebecca", gender: "girl", religion: "christian", meaning: "To bind, captivating", origin: "Hebrew", tag: "Biblical name" },
  { name: "Rachel", gender: "girl", religion: "christian", meaning: "Ewe, gentle one", origin: "Hebrew", tag: "Biblical name" },
  { name: "Ruth", gender: "girl", religion: "christian", meaning: "Compassionate friend", origin: "Hebrew", tag: "Biblical name" },
  { name: "Naomi", gender: "girl", religion: "christian", meaning: "Pleasantness", origin: "Hebrew", tag: "Biblical name" },
  { name: "Esther", gender: "girl", religion: "christian", meaning: "Star", origin: "Persian/Hebrew", tag: "Biblical name" },
  { name: "Abigail", gender: "girl", religion: "christian", meaning: "My father's joy", origin: "Hebrew", tag: "Biblical name" },
  { name: "Deborah", gender: "girl", religion: "christian", meaning: "Bee", origin: "Hebrew", tag: "Biblical name" },
  { name: "Miriam", gender: "girl", religion: "christian", meaning: "Wished-for child, beloved", origin: "Hebrew", tag: "Biblical name" },
  { name: "Grace", gender: "girl", religion: "christian", meaning: "God's grace, elegance", origin: "Latin" },
  { name: "Faith", gender: "girl", religion: "christian", meaning: "Trust, belief in God", origin: "English" },
  { name: "Hope", gender: "girl", religion: "christian", meaning: "Expectation, trust in God", origin: "English" },
  { name: "Charity", gender: "girl", religion: "christian", meaning: "Christian love, generosity", origin: "English" },
  { name: "Joy", gender: "girl", religion: "christian", meaning: "Great happiness", origin: "English" },
  { name: "Christina", gender: "girl", religion: "christian", meaning: "Follower of Christ", origin: "Greek/Latin" },
  { name: "Catherine", gender: "girl", religion: "christian", meaning: "Pure", origin: "Greek", tag: "Saint's name" },
  { name: "Margaret", gender: "girl", religion: "christian", meaning: "Pearl", origin: "Greek", tag: "Saint's name" },
  { name: "Teresa", gender: "girl", religion: "christian", meaning: "Harvester; late summer", origin: "Greek", tag: "Saint's name" },
  { name: "Cecilia", gender: "girl", religion: "christian", meaning: "Patroness of music", origin: "Latin", tag: "Saint's name" },
  { name: "Agnes", gender: "girl", religion: "christian", meaning: "Pure, holy", origin: "Greek", tag: "Saint's name" },
  { name: "Lucy", gender: "girl", religion: "christian", meaning: "Light", origin: "Latin", tag: "Saint's name" },
  { name: "Clare", gender: "girl", religion: "christian", meaning: "Bright, clear", origin: "Latin", tag: "Saint's name" },
  { name: "Rose", gender: "girl", religion: "christian", meaning: "The rose flower", origin: "Latin", tag: "Saint's name" },
  { name: "Veronica", gender: "girl", religion: "christian", meaning: "True image; bringer of victory", origin: "Latin/Greek", tag: "Saint's name" },
  { name: "Monica", gender: "girl", religion: "christian", meaning: "Advisor, counsellor", origin: "Latin", tag: "Saint's name" },
  { name: "Angela", gender: "girl", religion: "christian", meaning: "Messenger, angel", origin: "Greek" },
  { name: "Bernadette", gender: "girl", religion: "christian", meaning: "Brave as a bear", origin: "French", tag: "Saint's name" },
  { name: "Bridget", gender: "girl", religion: "christian", meaning: "Exalted one, strength", origin: "Irish", tag: "Saint's name" },
  { name: "Dorothy", gender: "girl", religion: "christian", meaning: "Gift of God", origin: "Greek" },
  { name: "Emma", gender: "girl", religion: "christian", meaning: "Whole, universal", origin: "Germanic" },
  { name: "Eva", gender: "girl", religion: "christian", meaning: "Life, living one", origin: "Hebrew", tag: "Biblical name" },
  { name: "Gloria", gender: "girl", religion: "christian", meaning: "Glory (to God)", origin: "Latin" },
  { name: "Irene", gender: "girl", religion: "christian", meaning: "Peace", origin: "Greek", tag: "Saint's name" },
  { name: "Julia", gender: "girl", religion: "christian", meaning: "Youthful", origin: "Latin" },
  { name: "Judith", gender: "girl", religion: "christian", meaning: "Woman of Judea, praised", origin: "Hebrew", tag: "Biblical name" },
  { name: "Lydia", gender: "girl", religion: "christian", meaning: "Woman from Lydia", origin: "Greek", tag: "Biblical name" },
  { name: "Madeline", gender: "girl", religion: "christian", meaning: "Woman of Magdala", origin: "Hebrew/Greek" },
  { name: "Natalie", gender: "girl", religion: "christian", meaning: "Born on Christmas Day", origin: "Latin" },
  { name: "Olivia", gender: "girl", religion: "christian", meaning: "Olive tree, symbol of peace", origin: "Latin" },
  { name: "Priscilla", gender: "girl", religion: "christian", meaning: "Ancient, venerable", origin: "Latin", tag: "Biblical name" },
  { name: "Rita", gender: "girl", religion: "christian", meaning: "Pearl (from Margarita)", origin: "Latin", tag: "Saint's name" },
  { name: "Sophia", gender: "girl", religion: "christian", meaning: "Wisdom", origin: "Greek" },
  { name: "Susanna", gender: "girl", religion: "christian", meaning: "Lily", origin: "Hebrew", tag: "Biblical name" },
  { name: "Tabitha", gender: "girl", religion: "christian", meaning: "Gazelle", origin: "Aramaic", tag: "Biblical name" },
  { name: "Victoria", gender: "girl", religion: "christian", meaning: "Victory", origin: "Latin" },
  { name: "Stella", gender: "girl", religion: "christian", meaning: "Star (Stella Maris — star of the sea)", origin: "Latin" },
  { name: "Angelina", gender: "girl", religion: "christian", meaning: "Little angel", origin: "Greek/Latin" },

  // ---------- Sikh — boys ----------
  { name: "Arjan", gender: "boy", religion: "sikh", meaning: "Earning, achievement; Guru Arjan Dev Ji", origin: "Punjabi", tag: "Guru's name" },
  { name: "Angad", gender: "boy", religion: "sikh", meaning: "Of one's own body; Guru Angad Dev Ji", origin: "Punjabi", tag: "Guru's name" },
  { name: "Gobind", gender: "boy", religion: "sikh", meaning: "Preserver of the world; Guru Gobind Singh Ji", origin: "Punjabi", tag: "Guru's name" },
  { name: "Harpreet", gender: "boy", religion: "sikh", meaning: "One who loves God", origin: "Punjabi" },
  { name: "Gurpreet", gender: "boy", religion: "sikh", meaning: "Love of the Guru", origin: "Punjabi" },
  { name: "Jaspreet", gender: "boy", religion: "sikh", meaning: "One who loves to sing praises", origin: "Punjabi" },
  { name: "Amarjeet", gender: "boy", religion: "sikh", meaning: "Forever victorious", origin: "Punjabi" },
  { name: "Baljeet", gender: "boy", religion: "sikh", meaning: "Victorious through strength", origin: "Punjabi" },
  { name: "Daljeet", gender: "boy", religion: "sikh", meaning: "Conqueror of armies", origin: "Punjabi" },
  { name: "Gurdeep", gender: "boy", religion: "sikh", meaning: "Lamp of the Guru", origin: "Punjabi" },
  { name: "Hardeep", gender: "boy", religion: "sikh", meaning: "Lamp of God", origin: "Punjabi" },
  { name: "Jagdeep", gender: "boy", religion: "sikh", meaning: "Lamp of the world", origin: "Punjabi" },
  { name: "Kuldeep", gender: "boy", religion: "sikh", meaning: "Lamp of the family", origin: "Punjabi" },
  { name: "Mandeep", gender: "boy", religion: "sikh", meaning: "Lamp of the mind", origin: "Punjabi" },
  { name: "Navdeep", gender: "boy", religion: "sikh", meaning: "New lamp, new light", origin: "Punjabi" },
  { name: "Sandeep", gender: "boy", religion: "sikh", meaning: "Lighted lamp, enlightened", origin: "Punjabi/Sanskrit" },
  { name: "Pardeep", gender: "boy", religion: "sikh", meaning: "Lamp, light", origin: "Punjabi" },
  { name: "Rajdeep", gender: "boy", religion: "sikh", meaning: "Lamp among kings", origin: "Punjabi" },
  { name: "Sukhdeep", gender: "boy", religion: "sikh", meaning: "Lamp of peace and comfort", origin: "Punjabi" },
  { name: "Amrik", gender: "boy", religion: "sikh", meaning: "Nectar; immortal", origin: "Punjabi" },
  { name: "Fateh", gender: "boy", religion: "sikh", meaning: "Victory", origin: "Punjabi/Persian" },
  { name: "Gurmeet", gender: "boy", religion: "sikh", meaning: "Friend of the Guru", origin: "Punjabi" },
  { name: "Harbhajan", gender: "boy", religion: "sikh", meaning: "One absorbed in God's worship", origin: "Punjabi" },
  { name: "Inderjit", gender: "boy", religion: "sikh", meaning: "Conqueror of Indra", origin: "Punjabi/Sanskrit" },
  { name: "Kartar", gender: "boy", religion: "sikh", meaning: "The Creator, master", origin: "Punjabi" },
  { name: "Manjit", gender: "boy", religion: "sikh", meaning: "Conqueror of the mind", origin: "Punjabi" },
  { name: "Onkar", gender: "boy", religion: "sikh", meaning: "The one supreme creator (Ik Onkar)", origin: "Punjabi" },
  { name: "Paramjit", gender: "boy", religion: "sikh", meaning: "Supremely victorious", origin: "Punjabi" },
  { name: "Ranjit", gender: "boy", religion: "sikh", meaning: "Victor in battle", origin: "Punjabi/Sanskrit" },
  { name: "Sarabjit", gender: "boy", religion: "sikh", meaning: "Victorious over everything", origin: "Punjabi" },
  { name: "Satnam", gender: "boy", religion: "sikh", meaning: "True name (of God)", origin: "Punjabi" },
  { name: "Sukhwinder", gender: "boy", religion: "sikh", meaning: "God of peace and happiness", origin: "Punjabi" },
  { name: "Tejinder", gender: "boy", religion: "sikh", meaning: "God of radiance and glory", origin: "Punjabi" },
  { name: "Ajit", gender: "boy", religion: "sikh", meaning: "Unconquerable", origin: "Punjabi/Sanskrit", tag: "Sahibzada name" },
  { name: "Jujhar", gender: "boy", religion: "sikh", meaning: "Warrior, one who fights on", origin: "Punjabi", tag: "Sahibzada name" },
  { name: "Zorawar", gender: "boy", religion: "sikh", meaning: "Powerful, brave", origin: "Punjabi/Persian", tag: "Sahibzada name" },
  { name: "Balwinder", gender: "boy", religion: "sikh", meaning: "God of strength", origin: "Punjabi" },
  { name: "Davinder", gender: "boy", religion: "sikh", meaning: "King of the gods", origin: "Punjabi" },
  { name: "Gurwinder", gender: "boy", religion: "sikh", meaning: "Guru, the lord of heaven", origin: "Punjabi" },
  { name: "Jaswant", gender: "boy", religion: "sikh", meaning: "Famous, praiseworthy", origin: "Punjabi/Sanskrit" },
  { name: "Kulwant", gender: "boy", religion: "sikh", meaning: "Of noble family", origin: "Punjabi" },
  { name: "Mohinder", gender: "boy", religion: "sikh", meaning: "Great god Indra", origin: "Punjabi/Sanskrit" },
  { name: "Rajinder", gender: "boy", religion: "sikh", meaning: "King of kings, lord Indra", origin: "Punjabi/Sanskrit" },
  { name: "Surinder", gender: "boy", religion: "sikh", meaning: "Chief of the gods", origin: "Punjabi/Sanskrit" },
  { name: "Joginder", gender: "boy", religion: "sikh", meaning: "Lord of yoga", origin: "Punjabi/Sanskrit" },
  { name: "Harman", gender: "boy", religion: "sikh", meaning: "Beloved of God", origin: "Punjabi" },
  { name: "Ekam", gender: "boy", religion: "sikh", meaning: "One, oneness of God", origin: "Punjabi" },
  { name: "Anhad", gender: "boy", religion: "sikh", meaning: "Unstruck divine sound, limitless", origin: "Punjabi" },
  { name: "Jashan", gender: "boy", religion: "sikh", meaning: "Celebration, festivity", origin: "Punjabi" },
  { name: "Harjot", gender: "boy", religion: "sikh", meaning: "Light of God", origin: "Punjabi" },

  // ---------- Sikh — girls ----------
  { name: "Simran", gender: "girl", religion: "sikh", meaning: "Remembrance of God, meditation", origin: "Punjabi" },
  { name: "Harleen", gender: "girl", religion: "sikh", meaning: "Absorbed in God's love", origin: "Punjabi" },
  { name: "Jasleen", gender: "girl", religion: "sikh", meaning: "Absorbed in singing God's praises", origin: "Punjabi" },
  { name: "Gurleen", gender: "girl", religion: "sikh", meaning: "Absorbed in the Guru", origin: "Punjabi" },
  { name: "Kirandeep", gender: "girl", religion: "sikh", meaning: "Lamp of light rays", origin: "Punjabi" },
  { name: "Amandeep", gender: "girl", religion: "sikh", meaning: "Lamp of peace", origin: "Punjabi" },
  { name: "Rupinder", gender: "girl", religion: "sikh", meaning: "Of the greatest beauty", origin: "Punjabi" },
  { name: "Kiranjit", gender: "girl", religion: "sikh", meaning: "Victorious ray of light", origin: "Punjabi" },
  { name: "Harsimran", gender: "girl", religion: "sikh", meaning: "Remembrance of God", origin: "Punjabi" },
  { name: "Gurnoor", gender: "girl", religion: "sikh", meaning: "Light of the Guru", origin: "Punjabi" },
  { name: "Harnoor", gender: "girl", religion: "sikh", meaning: "Light of God", origin: "Punjabi" },
  { name: "Amrit", gender: "girl", religion: "sikh", meaning: "Divine nectar, immortal", origin: "Punjabi" },
  { name: "Amrita", gender: "girl", religion: "sikh", meaning: "Immortal, full of nectar", origin: "Punjabi/Sanskrit" },
  { name: "Jasmeet", gender: "girl", religion: "sikh", meaning: "Famed friend", origin: "Punjabi" },
  { name: "Ravneet", gender: "girl", religion: "sikh", meaning: "Moral as the sun, ever-new virtue", origin: "Punjabi" },
  { name: "Navneet", gender: "girl", religion: "sikh", meaning: "Ever new, fresh", origin: "Punjabi/Sanskrit" },
  { name: "Harneet", gender: "girl", religion: "sikh", meaning: "God's virtue, godly conduct", origin: "Punjabi" },
  { name: "Prabhleen", gender: "girl", religion: "sikh", meaning: "Absorbed in the Lord", origin: "Punjabi" },
  { name: "Ramneet", gender: "girl", religion: "sikh", meaning: "Absorbed in God's virtue", origin: "Punjabi" },
  { name: "Sukhman", gender: "girl", religion: "sikh", meaning: "Peaceful mind", origin: "Punjabi" },
  { name: "Bani", gender: "girl", religion: "sikh", meaning: "The Guru's sacred word (Gurbani)", origin: "Punjabi" },
  { name: "Mehar", gender: "girl", religion: "sikh", meaning: "Grace, blessing, kindness", origin: "Punjabi/Persian" },
  { name: "Seerat", gender: "girl", religion: "sikh", meaning: "Inner beauty, character", origin: "Punjabi" },
  { name: "Anmol", gender: "girl", religion: "sikh", meaning: "Priceless, precious", origin: "Punjabi" },
  { name: "Pavneet", gender: "girl", religion: "sikh", meaning: "Pure, sacred conduct", origin: "Punjabi" },
  { name: "Gurbani", gender: "girl", religion: "sikh", meaning: "The Guru's holy words", origin: "Punjabi" },
  { name: "Parminder", gender: "girl", religion: "sikh", meaning: "Supreme god of heaven", origin: "Punjabi" },
  { name: "Manpreet", gender: "girl", religion: "sikh", meaning: "Love of the heart and mind", origin: "Punjabi" },
  { name: "Kamaljit", gender: "girl", religion: "sikh", meaning: "Victorious lotus, pure victory", origin: "Punjabi" },
  { name: "Sharanjit", gender: "girl", religion: "sikh", meaning: "Victory of taking God's shelter", origin: "Punjabi" },
  { name: "Amanjot", gender: "girl", religion: "sikh", meaning: "Light of peace", origin: "Punjabi" },
  { name: "Gurjot", gender: "girl", religion: "sikh", meaning: "Light of the Guru", origin: "Punjabi" },
  { name: "Simrat", gender: "girl", religion: "sikh", meaning: "Remembrance (of God)", origin: "Punjabi" },
  { name: "Jasnoor", gender: "girl", religion: "sikh", meaning: "Light of fame and praise", origin: "Punjabi" },
  { name: "Ekjot", gender: "girl", religion: "sikh", meaning: "One light, divine light", origin: "Punjabi" },
  { name: "Japji", gender: "girl", religion: "sikh", meaning: "Recitation; the morning prayer Japji Sahib", origin: "Punjabi" },
  { name: "Kirat", gender: "girl", religion: "sikh", meaning: "Honest work, praise", origin: "Punjabi" },
  { name: "Noorpreet", gender: "girl", religion: "sikh", meaning: "Love of divine light", origin: "Punjabi" },
  { name: "Rasleen", gender: "girl", religion: "sikh", meaning: "Absorbed in divine nectar", origin: "Punjabi" },
  { name: "Sahiba", gender: "girl", religion: "sikh", meaning: "Lady, respected woman", origin: "Punjabi" },
  { name: "Tejinder Kaur", gender: "girl", religion: "sikh", meaning: "God of glory (with Kaur — princess)", origin: "Punjabi" },
  { name: "Balpreet", gender: "girl", religion: "sikh", meaning: "One who loves strength/God", origin: "Punjabi" },
  { name: "Charanjit", gender: "girl", religion: "sikh", meaning: "Winning the Lord's feet (devotion)", origin: "Punjabi" },
  { name: "Dilpreet", gender: "girl", religion: "sikh", meaning: "Love of the heart", origin: "Punjabi" },
  { name: "Gagandeep", gender: "girl", religion: "sikh", meaning: "Lamp of the sky", origin: "Punjabi" },
  { name: "Harkirat", gender: "girl", religion: "sikh", meaning: "One who sings God's praises", origin: "Punjabi" },
  { name: "Ishmeet", gender: "girl", religion: "sikh", meaning: "Friend of God", origin: "Punjabi" },
  { name: "Jeevanjot", gender: "girl", religion: "sikh", meaning: "Light of life", origin: "Punjabi" },
  { name: "Livleen", gender: "girl", religion: "sikh", meaning: "Absorbed in God's love", origin: "Punjabi" },
  { name: "Mannat", gender: "girl", religion: "sikh", meaning: "Wish, prayer, vow", origin: "Punjabi" },
];
