export type AsmaName = {
  number: number;
  arabic: string;
  transliteration: string;
  meaning: string;
};

export const asmaUlHusna: AsmaName[] = [
  { number: 1, arabic: "الرَّحْمَن", transliteration: "Ar-Rahman", meaning: "The Most Compassionate" },
  { number: 2, arabic: "الرَّحِيم", transliteration: "Ar-Raheem", meaning: "The Most Merciful" },
  { number: 3, arabic: "الْمَلِك", transliteration: "Al-Malik", meaning: "The King, The Sovereign" },
  { number: 4, arabic: "الْقُدُّوس", transliteration: "Al-Quddus", meaning: "The Most Sacred, The Pure" },
  { number: 5, arabic: "السَّلَام", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { number: 6, arabic: "الْمُؤْمِن", transliteration: "Al-Mu'min", meaning: "The Granter of Security" },
  { number: 7, arabic: "الْمُهَيْمِن", transliteration: "Al-Muhaymin", meaning: "The Guardian, The Protector" },
  { number: 8, arabic: "الْعَزِيز", transliteration: "Al-Aziz", meaning: "The Almighty, The Honorable" },
  { number: 9, arabic: "الْجَبَّار", transliteration: "Al-Jabbar", meaning: "The Compeller, The Restorer" },
  { number: 10, arabic: "الْمُتَكَبِّر", transliteration: "Al-Mutakabbir", meaning: "The Supreme, The Majestic" },
  { number: 11, arabic: "الْخَالِق", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { number: 12, arabic: "الْبَارِئ", transliteration: "Al-Bari", meaning: "The Evolver, The Maker" },
  { number: 13, arabic: "الْمُصَوِّر", transliteration: "Al-Musawwir", meaning: "The Fashioner, The Shaper" },
  { number: 14, arabic: "الْغَفَّار", transliteration: "Al-Ghaffar", meaning: "The Ever-Forgiving" },
  { number: 15, arabic: "الْقَهَّار", transliteration: "Al-Qahhar", meaning: "The Subduer, The Ever-Dominant" },
  { number: 16, arabic: "الْوَهَّاب", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { number: 17, arabic: "الرَّزَّاق", transliteration: "Ar-Razzaq", meaning: "The Provider, The Sustainer" },
  { number: 18, arabic: "الْفَتَّاح", transliteration: "Al-Fattah", meaning: "The Opener, The Judge" },
  { number: 19, arabic: "اَلْعَلِيْم", transliteration: "Al-Alim", meaning: "The All-Knowing" },
  { number: 20, arabic: "الْقَابِض", transliteration: "Al-Qabid", meaning: "The Withholder, The Constrictor" },
  { number: 21, arabic: "الْبَاسِط", transliteration: "Al-Basit", meaning: "The Extender, The Expander" },
  { number: 22, arabic: "الْخَافِض", transliteration: "Al-Khafid", meaning: "The Abaser, The Humbler" },
  { number: 23, arabic: "الرَّافِع", transliteration: "Ar-Rafi'", meaning: "The Exalter, The Elevator" },
  { number: 24, arabic: "الْمُعِز", transliteration: "Al-Mu'izz", meaning: "The Honorer, The Bestower of Might" },
  { number: 25, arabic: "المُذِل", transliteration: "Al-Muzil", meaning: "The Humiliator, The Dishonorer" },
  { number: 26, arabic: "السَّمِيع", transliteration: "As-Sami", meaning: "The All-Hearing" },
  { number: 27, arabic: "الْبَصِير", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { number: 28, arabic: "الْحَكَم", transliteration: "Al-Hakam", meaning: "The Judge, The Arbitrator" },
  { number: 29, arabic: "الْعَدْل", transliteration: "Al-Adl", meaning: "The Utterly Just" },
  { number: 30, arabic: "اللَّطِيف", transliteration: "Al-Latif", meaning: "The Most Subtle, The Gentle" },
  { number: 31, arabic: "الْخَبِير", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { number: 32, arabic: "الْحَلِيم", transliteration: "Al-Halim", meaning: "The Forbearing, The Clement" },
  { number: 33, arabic: "الْعَظِيم", transliteration: "Al-Azim", meaning: "The Magnificent, The Supreme" },
  { number: 34, arabic: "الْغَفُور", transliteration: "Al-Ghafur", meaning: "The Great Forgiver" },
  { number: 35, arabic: "الشَّكُور", transliteration: "Ash-Shakur", meaning: "The Most Appreciative" },
  { number: 36, arabic: "الْعَلِيّ", transliteration: "Al-Ali", meaning: "The Most High" },
  { number: 37, arabic: "الْكَبِير", transliteration: "Al-Kabir", meaning: "The Most Great" },
  { number: 38, arabic: "الْحَفِيظ", transliteration: "Al-Hafiz", meaning: "The Preserver, The Guardian" },
  { number: 39, arabic: "المُقِيت", transliteration: "Al-Muqit", meaning: "The Sustainer, The Nourisher" },
  { number: 40, arabic: "الْحسِيب", transliteration: "Al-Hasib", meaning: "The Reckoner, The Accounter" },
  { number: 41, arabic: "الْجَلِيل", transliteration: "Al-Jalil", meaning: "The Majestic" },
  { number: 42, arabic: "الْكَرِيم", transliteration: "Al-Karim", meaning: "The Most Generous, The Bountiful" },
  { number: 43, arabic: "الرَّقِيب", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { number: 44, arabic: "الْمُجِيب", transliteration: "Al-Mujib", meaning: "The Responsive, The Answerer" },
  { number: 45, arabic: "الْوَاسِع", transliteration: "Al-Wasi", meaning: "The All-Encompassing, The Vast" },
  { number: 46, arabic: "الْحَكِيم", transliteration: "Al-Hakim", meaning: "The All-Wise" },
  { number: 47, arabic: "الْوَدُود", transliteration: "Al-Wadud", meaning: "The Most Loving" },
  { number: 48, arabic: "الْمَجِيد", transliteration: "Al-Majid", meaning: "The Most Glorious" },
  { number: 49, arabic: "الْبَاعِث", transliteration: "Al-Ba'ith", meaning: "The Resurrector, The Raiser of the Dead" },
  { number: 50, arabic: "الشَّهِيد", transliteration: "Ash-Shahid", meaning: "The All-Witnessing" },
  { number: 51, arabic: "الْحَقّ", transliteration: "Al-Haqq", meaning: "The Absolute Truth" },
  { number: 52, arabic: "الْوَكِيل", transliteration: "Al-Wakil", meaning: "The Trustee, The Disposer of Affairs" },
  { number: 53, arabic: "الْقَوِيّ", transliteration: "Al-Qawiyy", meaning: "The Most Strong" },
  { number: 54, arabic: "الْمَتِين", transliteration: "Al-Matin", meaning: "The Firm, The Steadfast" },
  { number: 55, arabic: "الْوَلِيّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend" },
  { number: 56, arabic: "الْحَمِيد", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { number: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The Accounter, The Reckoner of All Things" },
  { number: 58, arabic: "الْمُبْدِئ", transliteration: "Al-Mubdi", meaning: "The Originator, The Initiator" },
  { number: 59, arabic: "الْمُعِيد", transliteration: "Al-Mu'id", meaning: "The Restorer, The Reproducer" },
  { number: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { number: 61, arabic: "اَلْمُمِيت", transliteration: "Al-Mumit", meaning: "The Bringer of Death" },
  { number: 62, arabic: "الْحَيّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { number: 63, arabic: "الْقَيُّوم", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting, Sustainer of All" },
  { number: 64, arabic: "الْوَاجِد", transliteration: "Al-Wajid", meaning: "The Perceiver, The Finder" },
  { number: 65, arabic: "الْمَاجِد", transliteration: "Al-Majid", meaning: "The Illustrious, The Noble" },
  { number: 66, arabic: "الْواحِد", transliteration: "Al-Wahid", meaning: "The One, The Unique" },
  { number: 67, arabic: "اَلاَحَد", transliteration: "Al-Ahad", meaning: "The One, The Indivisible" },
  { number: 68, arabic: "الصَّمَد", transliteration: "As-Samad", meaning: "The Eternal, The Self-Sufficient" },
  { number: 69, arabic: "الْقَادِر", transliteration: "Al-Qadir", meaning: "The All-Able, The Omnipotent" },
  { number: 70, arabic: "الْمُقْتَدِر", transliteration: "Al-Muqtadir", meaning: "The All-Determiner, The Powerful" },
  { number: 71, arabic: "الْمُقَدِّم", transliteration: "Al-Muqaddim", meaning: "The Expediter, The Promoter" },
  { number: 72, arabic: "الْمُؤَخِّر", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer, The Postponer" },
  { number: 73, arabic: "الأَوَّل", transliteration: "Al-Awwal", meaning: "The First" },
  { number: 74, arabic: "الآخِر", transliteration: "Al-Akhir", meaning: "The Last" },
  { number: 75, arabic: "الظَّاهِر", transliteration: "Az-Zahir", meaning: "The Manifest, The Evident" },
  { number: 76, arabic: "الْبَاطِن", transliteration: "Al-Batin", meaning: "The Hidden, The Unmanifest" },
  { number: 77, arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor, The Protecting Ruler" },
  { number: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted" },
  { number: 79, arabic: "الْبَرّ", transliteration: "Al-Barr", meaning: "The Source of Goodness, The Most Kind" },
  { number: 80, arabic: "التَّوَّاب", transliteration: "At-Tawwab", meaning: "The Ever-Accepting of Repentance" },
  { number: 81, arabic: "الْمُنْتَقِم", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { number: 82, arabic: "العَفُوّ", transliteration: "Al-Afuww", meaning: "The Pardoner, The Effacer of Sins" },
  { number: 83, arabic: "الرَّؤُوف", transliteration: "Ar-Ra'uf", meaning: "The Most Kind, The Compassionate" },
  { number: 84, arabic: "مَالِكُ الْمُلْك", transliteration: "Malik-ul-Mulk", meaning: "Owner and Ruler of All Sovereignty" },
  { number: 85, arabic: "ذُوالْجَلَالِ وَالإكْرَام", transliteration: "Dhul-Jalali Wal-Ikram", meaning: "Lord of Majesty and Generosity" },
  { number: 86, arabic: "الْمُقْسِط", transliteration: "Al-Muqsit", meaning: "The Equitable, The Requiter" },
  { number: 87, arabic: "الْجَامِع", transliteration: "Al-Jami", meaning: "The Gatherer, The Uniter" },
  { number: 88, arabic: "الْغَنِيّ", transliteration: "Al-Ghani", meaning: "The Self-Sufficient, The Rich" },
  { number: 89, arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { number: 90, arabic: "الْمَانِع", transliteration: "Al-Mani", meaning: "The Preventer, The Withholder" },
  { number: 91, arabic: "الضَّار", transliteration: "Ad-Darr", meaning: "The Distresser, Creator of Harm" },
  { number: 92, arabic: "النَّافِع", transliteration: "An-Nafi", meaning: "The Propitious, Creator of Good" },
  { number: 93, arabic: "النُّور", transliteration: "An-Nur", meaning: "The Light" },
  { number: 94, arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { number: 95, arabic: "الْبَدِيع", transliteration: "Al-Badi", meaning: "The Incomparable Originator" },
  { number: 96, arabic: "اَلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { number: 97, arabic: "الْوَارِث", transliteration: "Al-Warith", meaning: "The Inheritor of All" },
  { number: 98, arabic: "الرَّشِيد", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path" },
  { number: 99, arabic: "الصَّبُور", transliteration: "As-Sabur", meaning: "The Most Patient" },
];
