/**
 * Curated related-tool mappings for every major tool.
 * Key: "category/slug"  →  Value: up to 6 "category/slug" strings.
 *
 * getRelatedTools() resolves these slugs against the live tools registry
 * and falls back to same-category tools when no manual entry is present.
 */
import { toolCategories } from "./tools-registry";

const RELATED_TOOLS_MAP: Record<string, string[]> = {
  // ── DAILY / FINANCE ───────────────────────────────────────────────
  "daily/emi-calculator": [
    "daily/loan-comparison",
    "daily/sip-calculator",
    "daily/simple-compound-interest",
    "daily/gst-calculator",
    "daily/salary-structure-optimizer",
    "generators/salary-slip-generator",
  ],
  "daily/sip-calculator": [
    "daily/emi-calculator",
    "daily/simple-compound-interest",
    "daily/loan-comparison",
    "daily/salary-structure-optimizer",
    "daily/percentage-calculator",
    "daily/gst-calculator",
  ],
  "daily/loan-comparison": [
    "daily/emi-calculator",
    "daily/sip-calculator",
    "daily/simple-compound-interest",
    "daily/gst-calculator",
    "daily/salary-structure-optimizer",
    "daily/percentage-calculator",
  ],
  "daily/simple-compound-interest": [
    "daily/emi-calculator",
    "daily/sip-calculator",
    "daily/loan-comparison",
    "daily/percentage-calculator",
    "daily/gst-calculator",
    "daily/salary-structure-optimizer",
  ],
  "daily/gst-calculator": [
    "daily/emi-calculator",
    "generators/invoice-generator",
    "generators/salary-slip-generator",
    "generators/rent-receipt-generator",
    "daily/percentage-calculator",
    "daily/salary-structure-optimizer",
  ],
  "daily/hra-calculator": [
    "daily/salary-structure-optimizer",
    "generators/rent-receipt-generator",
    "generators/salary-slip-generator",
    "daily/gst-calculator",
    "daily/emi-calculator",
    "daily/sip-calculator",
  ],
  "daily/salary-structure-optimizer": [
    "daily/hra-calculator",
    "generators/salary-slip-generator",
    "daily/emi-calculator",
    "daily/sip-calculator",
    "daily/gst-calculator",
    "daily/loan-comparison",
  ],
  "daily/salary-hourly-converter": [
    "daily/salary-structure-optimizer",
    "daily/hra-calculator",
    "generators/salary-slip-generator",
    "daily/percentage-calculator",
    "daily/tip-calculator",
    "daily/emi-calculator",
  ],
  "daily/currency-converter": [
    "daily/gst-calculator",
    "daily/percentage-calculator",
    "daily/emi-calculator",
    "daily/sip-calculator",
    "daily/tip-calculator",
    "daily/loan-comparison",
  ],

  // ── DAILY / GENERAL ───────────────────────────────────────────────
  "daily/age-calculator": [
    "daily/date-difference-calculator",
    "daily/bmi-calculator",
    "daily/countdown-timer",
    "islamic/hijri-converter",
    "daily/time-zone-converter",
    "daily/percentage-calculator",
  ],
  "daily/date-difference-calculator": [
    "daily/age-calculator",
    "daily/countdown-timer",
    "daily/time-zone-converter",
    "islamic/hijri-converter",
    "daily/bmi-calculator",
    "daily/percentage-calculator",
  ],
  "daily/countdown-timer": [
    "daily/date-difference-calculator",
    "daily/age-calculator",
    "daily/time-zone-converter",
    "daily/random-name-picker",
    "misc/certificate-qr-generator",
    "generators/invitation-card-maker",
  ],
  "daily/bmi-calculator": [
    "daily/percentage-calculator",
    "daily/tip-calculator",
    "daily/age-calculator",
    "daily/unit-converter",
    "daily/date-difference-calculator",
    "daily/salary-hourly-converter",
  ],
  "daily/tip-calculator": [
    "daily/percentage-calculator",
    "daily/bmi-calculator",
    "daily/age-calculator",
    "daily/currency-converter",
    "daily/unit-converter",
    "daily/gst-calculator",
  ],
  "daily/percentage-calculator": [
    "daily/tip-calculator",
    "daily/bmi-calculator",
    "daily/simple-compound-interest",
    "daily/gst-calculator",
    "daily/emi-calculator",
    "daily/salary-structure-optimizer",
  ],
  "daily/unit-converter": [
    "daily/bmi-calculator",
    "daily/percentage-calculator",
    "daily/date-difference-calculator",
    "daily/tip-calculator",
    "daily/salary-hourly-converter",
    "daily/time-zone-converter",
  ],
  "daily/time-zone-converter": [
    "daily/date-difference-calculator",
    "daily/countdown-timer",
    "daily/age-calculator",
    "daily/unit-converter",
    "daily/random-name-picker",
    "daily/word-counter",
  ],
  "daily/word-counter": [
    "daily/text-case-converter",
    "daily/lorem-ipsum-generator",
    "daily/password-generator",
    "misc/typing-speed-test",
    "misc/youtube-tag-generator",
    "generators/cover-letter-generator",
  ],
  "daily/text-case-converter": [
    "daily/word-counter",
    "daily/lorem-ipsum-generator",
    "daily/password-generator",
    "misc/typing-speed-test",
    "generators/cover-letter-generator",
    "generators/cv-resume-builder",
  ],
  "daily/lorem-ipsum-generator": [
    "daily/word-counter",
    "daily/text-case-converter",
    "daily/password-generator",
    "daily/color-palette-generator",
    "generators/letterhead-maker",
    "generators/invoice-generator",
  ],
  "daily/password-generator": [
    "daily/word-counter",
    "daily/text-case-converter",
    "daily/lorem-ipsum-generator",
    "daily/qr-generator",
    "daily/color-palette-generator",
    "json/formatter",
  ],
  "daily/color-palette-generator": [
    "daily/password-generator",
    "image/color-picker",
    "image/compress",
    "generators/visiting-card-maker",
    "generators/letterhead-maker",
    "image/favicon-generator",
  ],
  "daily/random-name-picker": [
    "daily/countdown-timer",
    "misc/certificate-qr-generator",
    "generators/certificate-maker",
    "daily/lorem-ipsum-generator",
    "daily/word-counter",
    "daily/password-generator",
  ],
  "daily/qr-generator": [
    "daily/barcode-generator",
    "image/favicon-generator",
    "misc/certificate-qr-generator",
    "generators/invoice-generator",
    "generators/visiting-card-maker",
    "image/compress",
  ],
  "daily/barcode-generator": [
    "daily/qr-generator",
    "generators/invoice-generator",
    "misc/certificate-qr-generator",
    "generators/visiting-card-maker",
    "image/favicon-generator",
    "generators/id-card-maker",
  ],
  "daily/json-formatter": [
    "json/formatter",
    "json/json-to-csv",
    "json/csv-to-json",
    "json/json-to-xml",
    "json/xml-to-json",
    "daily/password-generator",
  ],

  // ── PDF TOOLS ─────────────────────────────────────────────────────
  "pdf/merge": [
    "pdf/split",
    "pdf/compress",
    "pdf/pdf-to-image",
    "pdf/extract-pages",
    "pdf/reorder-pages",
    "image/image-to-pdf",
  ],
  "pdf/split": [
    "pdf/merge",
    "pdf/compress",
    "pdf/extract-pages",
    "pdf/delete-pages",
    "pdf/reorder-pages",
    "pdf/pdf-to-image",
  ],
  "pdf/compress": [
    "pdf/merge",
    "pdf/split",
    "pdf/pdf-to-image",
    "pdf/pdf-to-word",
    "image/compress",
    "pdf/extract-pages",
  ],
  "pdf/pdf-to-image": [
    "pdf/compress",
    "pdf/merge",
    "image/compress",
    "image/resize",
    "pdf/extract-pages",
    "image/convert",
  ],
  "pdf/image-to-pdf": [
    "pdf/merge",
    "pdf/compress",
    "image/compress",
    "image/resize",
    "image/image-to-pdf",
    "pdf/pdf-to-image",
  ],
  "pdf/pdf-to-word": [
    "pdf/merge",
    "pdf/compress",
    "pdf/extract-text",
    "pdf/pdf-to-image",
    "pdf/split",
    "markdown/convert",
  ],
  "pdf/protect": [
    "pdf/unlock",
    "pdf/merge",
    "pdf/watermark-add",
    "pdf/compress",
    "pdf/split",
    "pdf/page-numbers-add",
  ],
  "pdf/unlock": [
    "pdf/protect",
    "pdf/merge",
    "pdf/compress",
    "pdf/split",
    "pdf/pdf-to-word",
    "pdf/extract-text",
  ],
  "pdf/rotate": [
    "pdf/merge",
    "pdf/split",
    "pdf/reorder-pages",
    "pdf/delete-pages",
    "image/rotate-flip",
    "pdf/compress",
  ],
  "pdf/delete-pages": [
    "pdf/split",
    "pdf/extract-pages",
    "pdf/reorder-pages",
    "pdf/merge",
    "pdf/rotate",
    "pdf/compress",
  ],
  "pdf/reorder-pages": [
    "pdf/split",
    "pdf/delete-pages",
    "pdf/extract-pages",
    "pdf/merge",
    "pdf/rotate",
    "pdf/compress",
  ],
  "pdf/extract-pages": [
    "pdf/split",
    "pdf/delete-pages",
    "pdf/reorder-pages",
    "pdf/merge",
    "pdf/compress",
    "pdf/pdf-to-image",
  ],
  "pdf/extract-text": [
    "pdf/pdf-to-word",
    "pdf/compress",
    "pdf/merge",
    "pdf/split",
    "markdown/convert",
    "daily/word-counter",
  ],
  "pdf/watermark-add": [
    "pdf/protect",
    "pdf/page-numbers-add",
    "pdf/merge",
    "image/watermark",
    "pdf/compress",
    "generators/invoice-generator",
  ],
  "pdf/page-numbers-add": [
    "pdf/watermark-add",
    "pdf/merge",
    "pdf/split",
    "pdf/reorder-pages",
    "pdf/compress",
    "pdf/protect",
  ],
  "pdf/compare": [
    "pdf/extract-text",
    "pdf/pdf-to-word",
    "pdf/merge",
    "pdf/split",
    "json/formatter",
    "daily/word-counter",
  ],

  // ── IMAGE TOOLS ───────────────────────────────────────────────────
  "image/compress": [
    "image/resize",
    "image/convert",
    "image/crop",
    "pdf/compress",
    "image/exif-viewer-remover",
    "image/rotate-flip",
  ],
  "image/resize": [
    "image/compress",
    "image/crop",
    "image/convert",
    "image/rotate-flip",
    "generators/passport-photo-maker",
    "image/favicon-generator",
  ],
  "image/convert": [
    "image/compress",
    "image/resize",
    "image/crop",
    "pdf/pdf-to-image",
    "image/svg-to-png",
    "image/rotate-flip",
  ],
  "image/crop": [
    "image/resize",
    "image/compress",
    "image/rotate-flip",
    "generators/passport-photo-maker",
    "image/convert",
    "image/watermark",
  ],
  "image/watermark": [
    "image/compress",
    "image/resize",
    "pdf/watermark-add",
    "image/crop",
    "image/rotate-flip",
    "generators/invoice-generator",
  ],
  "image/to-base64": [
    "image/compress",
    "image/convert",
    "daily/qr-generator",
    "json/formatter",
    "image/favicon-generator",
    "image/svg-to-png",
  ],
  "image/rotate-flip": [
    "image/compress",
    "image/resize",
    "image/crop",
    "image/convert",
    "pdf/rotate",
    "image/grayscale-filter",
  ],
  "image/background-color-change": [
    "image/compress",
    "image/resize",
    "image/crop",
    "image/grayscale-filter",
    "image/watermark",
    "image/convert",
  ],
  "image/collage-maker": [
    "image/compress",
    "image/resize",
    "image/crop",
    "image/meme-generator",
    "generators/invitation-card-maker",
    "image/watermark",
  ],
  "image/meme-generator": [
    "image/collage-maker",
    "image/compress",
    "image/resize",
    "image/crop",
    "image/watermark",
    "daily/lorem-ipsum-generator",
  ],
  "image/color-picker": [
    "daily/color-palette-generator",
    "image/compress",
    "image/convert",
    "image/favicon-generator",
    "image/grayscale-filter",
    "image/background-color-change",
  ],
  "image/favicon-generator": [
    "image/compress",
    "image/resize",
    "image/convert",
    "daily/qr-generator",
    "image/svg-to-png",
    "generators/visiting-card-maker",
  ],
  "image/image-to-pdf": [
    "pdf/merge",
    "pdf/compress",
    "image/compress",
    "image/resize",
    "pdf/pdf-to-image",
    "pdf/image-to-pdf",
  ],
  "image/exif-viewer-remover": [
    "image/compress",
    "image/resize",
    "image/convert",
    "image/rotate-flip",
    "image/crop",
    "image/grayscale-filter",
  ],
  "image/grayscale-filter": [
    "image/compress",
    "image/resize",
    "image/convert",
    "image/rotate-flip",
    "image/background-color-change",
    "pdf/compress",
  ],
  "image/svg-to-png": [
    "image/convert",
    "image/compress",
    "image/resize",
    "image/favicon-generator",
    "image/to-base64",
    "image/rotate-flip",
  ],

  // ── ISLAMIC TOOLS ─────────────────────────────────────────────────
  "islamic/zakat-calculator": [
    "islamic/inheritance-calculator",
    "islamic/property-land-distribution",
    "islamic/hijri-converter",
    "islamic/prayer-times",
    "daily/emi-calculator",
    "daily/percentage-calculator",
  ],
  "islamic/hijri-converter": [
    "islamic/prayer-times",
    "islamic/ramadan-calendar",
    "daily/age-calculator",
    "daily/date-difference-calculator",
    "islamic/zakat-calculator",
    "islamic/salah-time-reminder",
  ],
  "islamic/99-names": [
    "islamic/tasbih-counter",
    "islamic/prayer-times",
    "misc/baby-name-generator",
    "islamic/hijri-converter",
    "islamic/ramadan-calendar",
    "islamic/qibla-direction",
  ],
  "islamic/tasbih-counter": [
    "islamic/99-names",
    "islamic/prayer-times",
    "islamic/salah-time-reminder",
    "islamic/qibla-direction",
    "islamic/ramadan-calendar",
    "islamic/hijri-converter",
  ],
  "islamic/inheritance-calculator": [
    "islamic/zakat-calculator",
    "islamic/property-land-distribution",
    "islamic/hijri-converter",
    "daily/percentage-calculator",
    "daily/emi-calculator",
    "misc/rental-roi-calculator",
  ],
  "islamic/property-land-distribution": [
    "islamic/inheritance-calculator",
    "islamic/zakat-calculator",
    "daily/percentage-calculator",
    "misc/rental-roi-calculator",
    "daily/emi-calculator",
    "misc/society-maintenance-calculator",
  ],
  "islamic/prayer-times": [
    "islamic/qibla-direction",
    "islamic/ramadan-calendar",
    "islamic/salah-time-reminder",
    "islamic/hijri-converter",
    "islamic/tasbih-counter",
    "islamic/99-names",
  ],
  "islamic/qibla-direction": [
    "islamic/prayer-times",
    "islamic/ramadan-calendar",
    "islamic/salah-time-reminder",
    "islamic/hijri-converter",
    "misc/distance-calculator",
    "islamic/tasbih-counter",
  ],
  "islamic/ramadan-calendar": [
    "islamic/prayer-times",
    "islamic/qibla-direction",
    "islamic/salah-time-reminder",
    "islamic/hijri-converter",
    "daily/countdown-timer",
    "islamic/tasbih-counter",
  ],
  "islamic/salah-time-reminder": [
    "islamic/prayer-times",
    "islamic/ramadan-calendar",
    "islamic/qibla-direction",
    "islamic/hijri-converter",
    "islamic/tasbih-counter",
    "daily/countdown-timer",
  ],

  // ── GENERATORS & DOCUMENTS ────────────────────────────────────────
  "generators/invoice-generator": [
    "generators/salary-slip-generator",
    "generators/rent-receipt-generator",
    "generators/offer-letter-generator",
    "daily/gst-calculator",
    "daily/emi-calculator",
    "generators/letterhead-maker",
  ],
  "generators/salary-slip-generator": [
    "generators/invoice-generator",
    "generators/rent-receipt-generator",
    "generators/offer-letter-generator",
    "daily/salary-structure-optimizer",
    "daily/hra-calculator",
    "daily/gst-calculator",
  ],
  "generators/cv-resume-builder": [
    "generators/cover-letter-generator",
    "generators/offer-letter-generator",
    "generators/certificate-maker",
    "generators/id-card-maker",
    "generators/noc-letter-generator",
    "generators/signature-generator",
  ],
  "generators/cover-letter-generator": [
    "generators/cv-resume-builder",
    "generators/offer-letter-generator",
    "generators/noc-letter-generator",
    "generators/salary-slip-generator",
    "generators/certificate-maker",
    "daily/word-counter",
  ],
  "generators/rent-receipt-generator": [
    "generators/invoice-generator",
    "generators/salary-slip-generator",
    "daily/hra-calculator",
    "daily/gst-calculator",
    "generators/letterhead-maker",
    "generators/offer-letter-generator",
  ],
  "generators/offer-letter-generator": [
    "generators/cv-resume-builder",
    "generators/cover-letter-generator",
    "generators/noc-letter-generator",
    "generators/salary-slip-generator",
    "generators/certificate-maker",
    "generators/letterhead-maker",
  ],
  "generators/noc-letter-generator": [
    "generators/offer-letter-generator",
    "generators/cover-letter-generator",
    "generators/cv-resume-builder",
    "generators/letterhead-maker",
    "generators/certificate-maker",
    "generators/salary-slip-generator",
  ],
  "generators/certificate-maker": [
    "generators/id-card-maker",
    "generators/cv-resume-builder",
    "generators/offer-letter-generator",
    "misc/certificate-qr-generator",
    "generators/signature-generator",
    "generators/letterhead-maker",
  ],
  "generators/id-card-maker": [
    "generators/certificate-maker",
    "generators/visiting-card-maker",
    "generators/passport-photo-maker",
    "daily/qr-generator",
    "generators/signature-generator",
    "image/crop",
  ],
  "generators/visiting-card-maker": [
    "generators/id-card-maker",
    "generators/letterhead-maker",
    "generators/invoice-generator",
    "daily/qr-generator",
    "daily/color-palette-generator",
    "image/favicon-generator",
  ],
  "generators/letterhead-maker": [
    "generators/visiting-card-maker",
    "generators/invoice-generator",
    "generators/offer-letter-generator",
    "generators/noc-letter-generator",
    "generators/salary-slip-generator",
    "image/compress",
  ],
  "generators/signature-generator": [
    "generators/certificate-maker",
    "generators/cv-resume-builder",
    "generators/id-card-maker",
    "pdf/watermark-add",
    "generators/offer-letter-generator",
    "image/compress",
  ],
  "generators/invitation-card-maker": [
    "image/collage-maker",
    "generators/certificate-maker",
    "generators/visiting-card-maker",
    "daily/countdown-timer",
    "daily/qr-generator",
    "image/compress",
  ],
  "generators/passport-photo-maker": [
    "image/resize",
    "image/crop",
    "generators/id-card-maker",
    "image/compress",
    "image/convert",
    "image/rotate-flip",
  ],
  "generators/marriage-biodata-maker": [
    "generators/cv-resume-builder",
    "generators/certificate-maker",
    "generators/invitation-card-maker",
    "misc/baby-name-generator",
    "generators/signature-generator",
    "generators/passport-photo-maker",
  ],

  // ── MISC & EDUCATIONAL ────────────────────────────────────────────
  "misc/fuel-cost-calculator": [
    "misc/distance-calculator",
    "misc/solar-panel-savings-calculator",
    "daily/percentage-calculator",
    "daily/unit-converter",
    "misc/rental-roi-calculator",
    "daily/tip-calculator",
  ],
  "misc/distance-calculator": [
    "misc/fuel-cost-calculator",
    "daily/unit-converter",
    "daily/time-zone-converter",
    "islamic/qibla-direction",
    "misc/solar-panel-savings-calculator",
    "daily/percentage-calculator",
  ],
  "misc/solar-panel-savings-calculator": [
    "misc/fuel-cost-calculator",
    "daily/emi-calculator",
    "daily/sip-calculator",
    "misc/rental-roi-calculator",
    "daily/percentage-calculator",
    "daily/unit-converter",
  ],
  "misc/rental-roi-calculator": [
    "daily/emi-calculator",
    "daily/sip-calculator",
    "misc/society-maintenance-calculator",
    "daily/loan-comparison",
    "daily/simple-compound-interest",
    "daily/percentage-calculator",
  ],
  "misc/society-maintenance-calculator": [
    "misc/rental-roi-calculator",
    "daily/emi-calculator",
    "daily/percentage-calculator",
    "daily/gst-calculator",
    "generators/invoice-generator",
    "daily/sip-calculator",
  ],
  "misc/baby-name-generator": [
    "islamic/99-names",
    "misc/numerology-calculator",
    "generators/marriage-biodata-maker",
    "generators/invitation-card-maker",
    "generators/certificate-maker",
    "daily/countdown-timer",
  ],
  "misc/numerology-calculator": [
    "misc/baby-name-generator",
    "daily/age-calculator",
    "daily/date-difference-calculator",
    "misc/typing-speed-test",
    "daily/percentage-calculator",
    "generators/cv-resume-builder",
  ],
  "misc/typing-speed-test": [
    "daily/word-counter",
    "daily/text-case-converter",
    "misc/youtube-tag-generator",
    "daily/lorem-ipsum-generator",
    "misc/numerology-calculator",
    "generators/cv-resume-builder",
  ],
  "misc/youtube-tag-generator": [
    "daily/word-counter",
    "daily/qr-generator",
    "misc/typing-speed-test",
    "daily/text-case-converter",
    "generators/visiting-card-maker",
    "daily/countdown-timer",
  ],
  "misc/aadhaar-masking-tool": [
    "misc/pan-aadhaar-name-matcher",
    "image/compress",
    "image/crop",
    "image/exif-viewer-remover",
    "generators/id-card-maker",
    "pdf/protect",
  ],
  "misc/pan-aadhaar-name-matcher": [
    "misc/aadhaar-masking-tool",
    "daily/word-counter",
    "daily/text-case-converter",
    "generators/id-card-maker",
    "misc/numerology-calculator",
    "pdf/protect",
  ],
  "misc/certificate-qr-generator": [
    "daily/qr-generator",
    "generators/certificate-maker",
    "daily/barcode-generator",
    "generators/id-card-maker",
    "generators/visiting-card-maker",
    "daily/countdown-timer",
  ],
  "misc/solar-system-explorer": [
    "daily/unit-converter",
    "daily/percentage-calculator",
    "misc/distance-calculator",
    "misc/numerology-calculator",
    "daily/age-calculator",
    "daily/countdown-timer",
  ],

  // ── JSON TOOLS ────────────────────────────────────────────────────
  "json/formatter": [
    "json/json-to-csv",
    "json/csv-to-json",
    "json/json-to-xml",
    "json/xml-to-json",
    "daily/json-formatter",
    "daily/word-counter",
  ],
  "json/json-to-csv": [
    "json/csv-to-json",
    "json/formatter",
    "json/json-to-xml",
    "json/xml-to-json",
    "markdown/convert",
    "daily/json-formatter",
  ],
  "json/csv-to-json": [
    "json/json-to-csv",
    "json/formatter",
    "json/json-to-xml",
    "json/xml-to-json",
    "markdown/convert",
    "daily/json-formatter",
  ],
  "json/json-to-xml": [
    "json/xml-to-json",
    "json/formatter",
    "json/json-to-csv",
    "json/csv-to-json",
    "daily/json-formatter",
    "markdown/convert",
  ],
  "json/xml-to-json": [
    "json/json-to-xml",
    "json/formatter",
    "json/json-to-csv",
    "json/csv-to-json",
    "daily/json-formatter",
    "markdown/convert",
  ],

  // ── MARKDOWN ──────────────────────────────────────────────────────
  "markdown/convert": [
    "pdf/pdf-to-word",
    "pdf/extract-text",
    "json/formatter",
    "json/csv-to-json",
    "daily/word-counter",
    "daily/text-case-converter",
  ],
};

export type RelatedTool = {
  name: string;
  href: string;
  description: string;
};

/**
 * Returns up to 6 related tools for a given category/slug combination.
 * Uses the curated map above; falls back to same-category tools when
 * no manual entry is present (excluding the current tool).
 */
export function getRelatedTools(
  categorySlug: string,
  toolSlug: string
): RelatedTool[] {
  // Build a flat lookup: "category/slug" → tool metadata
  const toolMap = new Map<string, RelatedTool>();
  for (const cat of toolCategories) {
    for (const tool of cat.tools) {
      if (tool.status === "live") {
        toolMap.set(`${cat.slug}/${tool.slug}`, {
          name: tool.name,
          href: `/tools/${cat.slug}/${tool.slug}`,
          description: tool.description,
        });
      }
    }
  }

  const key = `${categorySlug}/${toolSlug}`;
  const manualList = RELATED_TOOLS_MAP[key];

  let slugs: string[];
  if (manualList) {
    slugs = manualList;
  } else {
    // Auto-fallback: same-category tools, excluding the current one
    const cat = toolCategories.find((c) => c.slug === categorySlug);
    slugs = (cat?.tools ?? [])
      .filter((t) => t.slug !== toolSlug && t.status === "live")
      .slice(0, 6)
      .map((t) => `${categorySlug}/${t.slug}`);
  }

  return slugs
    .map((s) => toolMap.get(s))
    .filter((t): t is RelatedTool => Boolean(t))
    .slice(0, 6);
}
